version: "3.7"

services: 
    db:
        image: postgres
        container_name: rentalxDB
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=senhabonita
            - POSTGRES_DB=rentalx
        volumes: 
            - pgdata:/data/postgres
    app:
        build: .
        container_name: rentalx
        ports: 
            - 3030:3030
        volumes: 
            - .:/usr/app
        links: 
            - db
        depends_on: 
            - db
volumes: 
    pgdata:
        driver: local